[package]
name = "tmptest"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tools = { path = "../tools" }